spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        json:
          use:
            type:
              headers: false
      group-id: group-test
      auto-offset-reset: earliest


SUBSCRIBED_TOPIC: TEST.TOPIC